name: UDTS-test

on:
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    name: linux-on-pr-test
    runs-on: ubuntu-latest
    outputs:
      build_time: ${{ steps.build_vars.outputs.build_time }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: 'pipenv'
          cache-dependency-path: '**/Pipfile'
          
      - name: Setup Pipenv
        run: |
          python -m pip install -U pip pipenv
          pipenv install --deploy -d
      - name: Test
        run: pipenv run pytest tests.py
